# Generated by Django 4.1.7 on 2023-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TlgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlg_id', models.CharField(max_length=30, verbose_name='TG ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Telegram его проверил')),
                ('is_scam', models.BooleanField(default=False, verbose_name='Мошенник')),
                ('is_fake', models.BooleanField(default=False, verbose_name='Выдаёт себя за другого')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя(TG)')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия(TG)')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='username(TG)')),
                ('language_code', models.CharField(blank=True, max_length=20, verbose_name='языковой код(TG)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'пользователь TG',
                'verbose_name_plural': 'пользователи TG',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VpnBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=230, verbose_name='Ключ')),
                ('value', models.TextField(max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'настройка Redirect Bot',
                'verbose_name_plural': 'настройки Redirect Bot',
                'ordering': ['-id'],
            },
        ),
    ]
