# Generated by Django 4.1.7 on 2023-03-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0003_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=1000, verbose_name='Ссылка'),
        ),
    ]
