# Generated by Django 4.1.7 on 2023-03-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0004_alter_links_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='tlg_user',
            new_name='tlg_id',
        ),
        migrations.CreateModel(
            name='LinkSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название набора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('tlg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect_admin.tlguser', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Набор ссылок',
                'verbose_name_plural': 'Наборы ссылок',
                'ordering': ['-id'],
            },
        ),
    ]
