# Generated by Django 4.1.7 on 2023-03-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0005_rename_tlg_user_links_tlg_id_linkset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkset',
            old_name='tlg_user',
            new_name='tlg_id',
        ),
        migrations.AddField(
            model_name='links',
            name='link_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='redirect_admin.linkset', verbose_name='Набор ссылок'),
            preserve_default=False,
        ),
    ]
