# Generated by Django 4.1.7 on 2023-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0006_rename_tlg_user_linkset_tlg_id_links_link_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='redirect_numb',
            field=models.IntegerField(default=0, verbose_name='Кол-во редиректов'),
            preserve_default=False,
        ),
    ]
