# Generated by Django 4.1.7 on 2023-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0007_links_redirect_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='company_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID компании(keitaro)'),
        ),
        migrations.AddField(
            model_name='links',
            name='redirect_links',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Редирект ссылки'),
        ),
        migrations.AddField(
            model_name='links',
            name='short_link_service',
            field=models.CharField(blank=True, choices=[('cutt.ly', 'cutt.ly'), ('cutt.us', 'cutt.us'), ('clck.ru', 'clck.ru'), ('kortlink.dk', 'kortlink.dk'), ('gg.gg', 'gg.gg'), ('t9y.me', 't9y.me')], max_length=11, null=True, verbose_name='Сервис сокращения ссылок'),
        ),
        migrations.AddField(
            model_name='links',
            name='short_links',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Сокращённые ссылки'),
        ),
    ]
