# Generated by Django 4.1.7 on 2023-03-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0008_links_company_id_links_redirect_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='redirect_links',
            field=models.TextField(blank=True, max_length=25000, null=True, verbose_name='Редирект ссылки'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_links',
            field=models.TextField(blank=True, max_length=25000, null=True, verbose_name='Сокращённые ссылки'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_system_type', models.CharField(choices=[('qiwi', 'QIWI'), ('crystal', 'Crystal Pay'), ('to_card', 'Перевод на карту')], max_length=7, verbose_name='Платёжная сис-ма')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа(руб.)')),
                ('bill_id', models.CharField(max_length=350, verbose_name='ID счёта на оплату')),
                ('bill_status', models.BooleanField(default=False, verbose_name='Счёт оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('tlg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect_admin.tlguser', verbose_name='Чей платёж')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-id'],
            },
        ),
    ]
