# Generated by Django 4.1.7 on 2023-03-28 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0010_payments_archived_payments_bill_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='bill_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=500, verbose_name='Ссылка счёта'),
            preserve_default=False,
        ),
    ]
