# Generated by Django 4.1.7 on 2023-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0011_payments_bill_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='bill_expire_at',
            field=models.DateTimeField(verbose_name='Дата аннулирования счёта на оплату'),
        ),
    ]
