# Generated by Django 4.1.7 on 2023-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0012_alter_payments_bill_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_link_service',
            field=models.CharField(blank=True, choices=[('cutt.ly', 'cutt.ly'), ('cutt.us', 'cutt.us'), ('clck.ru', 'clck.ru'), ('kortlink.dk', 'kortlink.dk'), ('gg.gg', 'gg.gg'), ('t9y.me', 't9y.me'), ('custom_domain', 'custom_domain')], max_length=14, null=True, verbose_name='Сервис сокращения ссылок'),
        ),
    ]
