# Generated by Django 4.1.7 on 2024-03-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0015_alter_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=5, verbose_name='языковой код')),
                ('language', models.CharField(max_length=25, verbose_name='язык')),
            ],
            options={
                'verbose_name': 'язык интерфейса',
                'verbose_name_plural': 'языки интерфейса',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tlguser',
            name='interface_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redirect_admin.interfacelanguages', verbose_name='язык интерфейса'),
        ),
    ]
