# Generated by Django 4.1.7 on 2024-03-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0016_interfacelanguages_tlguser_interface_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacelanguages',
            name='default_language',
            field=models.BooleanField(default=False, verbose_name='дефолтный язык'),
        ),
    ]
