# Generated by Django 4.1.7 on 2025-01-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0017_interfacelanguages_default_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(verbose_name='Домен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('tlg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect_admin.tlguser', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Домен пользователя',
                'verbose_name_plural': 'Домены пользователей',
                'ordering': ['-id'],
            },
        ),
    ]
