# Generated by Django 4.1.7 on 2025-01-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0018_userdomains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdomains',
            old_name='tlg_id',
            new_name='tlg_user',
        ),
    ]
