# Generated by Django 4.1.7 on 2025-02-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0019_rename_tlg_id_userdomains_tlg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdomains',
            name='claudflare_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID в ClaudFlare'),
        ),
        migrations.AddField(
            model_name='userdomains',
            name='keitaro_id',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='ID в KEITARO'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_link_service',
            field=models.CharField(blank=True, choices=[('cutt.ly', 'cutt.ly'), ('cutt.us', 'cutt.us'), ('clck.ru', 'clck.ru'), ('kortlink.dk', 'kortlink.dk'), ('gg.gg', 'gg.gg'), ('t9y.me', 't9y.me'), ('custom_domain', 'custom_domain'), ('user_domain', 'user_domain')], max_length=14, null=True, verbose_name='Сервис сокращения ссылок'),
        ),
    ]
