# Generated by Django 4.1.7 on 2025-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0020_userdomains_claudflare_id_userdomains_keitaro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdomains',
            name='claudflare_zone_dns_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID DNS в ClaudFlare'),
        ),
    ]
