# Generated by Django 4.1.7 on 2025-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0021_userdomains_claudflare_zone_dns_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectbotsettings',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
    ]
