# Generated by Django 4.1.7 on 2025-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_admin', '0022_alter_redirectbotsettings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectbotsettings',
            name='value',
            field=models.TextField(max_length=5000, verbose_name='Значение'),
        ),
    ]
